# Site settings
title: Git for Humans - Resources
email: david@demaree.me
description: > # this means to ignore newlines until "baseurl:"
  A website of living references for an upcoming book about Git
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://gitforhumans.info" # the base hostname & protocol for your site
twitter_username: ddemaree
github_username:  ddemaree

# Build settings
markdown: kramdown

exclude: ["bin", "Gemfile*", "Vagrantfile"]